### ISSUE TITLE
Pre-defined words to ignore when using google?

### ISSUE THREAD

**Issue by mstanislav** [badsyntax/jquery-spellchecker#15]
Just wondering if there's a way to create a word-list to ignore by default so that when using google we can skip some hassle for our users having to ignore the same acronyms and capitalizations that get flagged every time. Great plugin!

**Comment by badsyntax** [comment]
Good idea! I will incorporate this feature soon, at which point I'll update this ticket, so stay tuned! (I also gladly accept pull requests if you're willing to make this change yourself.)

**Comment by mstanislav** [comment]
I think this may not be coming.. :)
