### ISSUE TITLE
CKEditor issues

### ISSUE THREAD

**Issue by khalidabuhakmeh** [badsyntax/jquery-spellchecker#16]
I tried integrating this with CKEditor and found a lot of issues. So much so that I couldn't use it. I was switching from Redactor over to CKeditor.
- Once the content becomes greater than the size of the editor, the suggest box positioning is wrong.
- Once the content becomes greater than the size of the editor, the selected word is wrong (big one).

I had implemented a .Net backend for this which worked with Redactor, but since it doesn't work with CKEditor I am forced to used another provider.

**Comment by badsyntax** [comment]
I'm sorry you've had problems, but thanks for letting me know about them. I have stated this is a beta release so i expect there will be some issues. The issues you mentioned seem easily solvable and i will fix them.

**Comment by khalidabuhakmeh** [comment]
Sorry I just feel defeated. I've been working on this for a day under a tight deadline crunch and it kicked my ass. I appreciate the work you've put in.

**Comment by badsyntax** [comment]
I've made some changes that I think have fixed the issues you have mentioned. 

Please can you test here: http://jquery-spellchecker.badsyntax.co/ckeditor.html

Or use the following two files from the development branch:
- Spellchecker plugin: https://raw.github.com/badsyntax/jquery-spellchecker/develop/src/js/jquery.spellchecker.js
- CKEditor spellchecker plugin: https://raw.github.com/badsyntax/jquery-spellchecker/develop/src/examples/english/ckeditor/plugins/jqueryspellchecker/plugin.js

**Comment by mcka** [comment]
multiple ckeditor instances do not work properly. one affects another's underlined words
