### ISSUE TITLE
Calling SpellChecker.php remotely

### ISSUE THREAD

**Issue by carlospictor** [badsyntax/jquery-spellchecker#18]
Hi,

Have almost managed to integrate the spellchecker into a Redactor set-up. 

I do though have one remaining issues, and I'm hoping you can offer some pointers.

I need to run the text editor with spellchecker on a page that is not PHP, sitting on a different server to where I have got spellchecker and the SpellChecker.php service installed.  The spellcheck seems to work, but each time the check spelling button is pressed I can see that two AJAX calls are made:

The first one is a POST which returns the JSON object of mis-spelled words. This also returns a 301 moved permanently response.

A second request, this time a GET is then fired, which never completes - just sitting in the background waiting for a response.

On the server running the text editor, I am tunnelling the request throgh a proxy script to avoid cross-site scripting issues - posting directly to SpellChecker.php on the remote server.

Do you have any thoughts what might be causing the double firing of AJAX requests, or any pointers to how I could directly call SpellChecker.php from a remote server?

**Comment by carlospictor** [comment]
Thinking further, I'm guessing that the SpellChecker.php file itself calls/posts/submits to other files (Driver.php, Request.php etc) and that by attempting to tunnel via a proxy script on the local server, those redirects are getting messed up?

**Comment by badsyntax** [comment]
The SpellChecker,php file does not send additional requests to the drivers. It's all handled in one request. Thus, it shouldn't matter if you're proxying the request on a different server, as long as you're sending the correct POST request to the SpellChecker.php file. 
The 301 redirect sounds like it might be the cause of your problems, which is coming from your proxy. 

If you can post debug information or screenshots (or a link), I might be able to advise further..

**Comment by carlospictor** [comment]
Thanks for replying.

I've done loads of different tests today trying to figure out the problem, and have identified the problem, but not a solution.

It would appear that in our CMS, any $.ajax() POST calls that pass four or more parameters in the data{} property result in a 301 which then redirects to itself as a GET request. It doesn't even matter what the parameters are, so long as there are no more than 3. Absolutely maddening, but nothing wrong with the spellchecker!

Sorry to have wasted your time, I'll close this.

**Comment by badsyntax** [comment]
Maddening indeed! I'm thinking about changing the requests and webservices to be more REST-like which will probably result in sending only a request body in the form of JSON. This could possibly resolve your issues. I can't say when I will get around to doing that though. In the meantime, I hope you can you sort out the issues!
