### ISSUE TITLE
Inline suggestion for spell check in textarea

### ISSUE THREAD

**Issue by dhaneesh** [badsyntax/jquery-spellchecker#25]
Hi,

I have successfully implemented jquery spell checker plugin for textarea. Can I integrate the suggestion box inline in textarea same as that for html example.(http://jquery-spellchecker.badsyntax.co/basic/html-pspell.html) ?

**Comment by johan-ludvigsson-stratsys** [comment]
No, because textarea can't support HTML-tags and format in order to style inline.

**Comment by badsyntax** [comment]
As @johan-ludvigsson-stratsys this is not possible for many reasons.

Rather use a RTE/WYSIWYG instead, or just use a &lt;div&gt; with contentEditable property (which is pretty well supported: http://caniuse.com/contenteditable).
