### ISSUE TITLE
hunspell integration

### ISSUE THREAD

**Issue by giorgio79** [badsyntax/jquery-spellchecker#3]
I heard lots of praises for hunspell. Maybe down the line an integration would be great. I may look into it as well in some weeks :)

http://en.wikipedia.org/wiki/Hunspell
http://hunspell.sourceforge.net/

Installation
http://www.protung.ro/2009/08/php-spell-checker/

**Comment by badsyntax** [comment]
Thanks for introducing me to hunspell, it looks like a good library. I'm very willing to take pull requests if you're up for creating a new PHP driver.
