### ISSUE TITLE
defaultConfig is rewritten upon creating a spellchecker

### ISSUE THREAD

**Issue by johan-ludvigsson-stratsys** [badsyntax/jquery-spellchecker#31]
In the constructor for Spellchecker, the following code can be found

this.config = $.extend(true, defaultConfig, config);

This rewrites the defaultConfig with the values of config. It is solved by creating a copy first to extend from;

```
    var defaultConfigCopy = $.extend(true, {}, defaultConfig);
    this.config = $.extend(true, defaultConfigCopy, config);
```

EDIT: Missed true parameter for deep copy

**Comment by badsyntax** [comment]
Thanks for this bug report, fixed with pull-request https://github.com/badsyntax/jquery-spellchecker/pull/32.
