### ISSUE TITLE
Integrate with php enchant instead of pspell or hunspell directly

### ISSUE THREAD

**Issue by giorgio79** [badsyntax/jquery-spellchecker#5]
Hello,

Been thinking about this issue https://github.com/badsyntax/jquery-spellchecker/issues/3, and probably php enchant would be an even better php integration than hunspell or pspell...
http://www.php.net/manual/en/intro.enchant.php
http://www.php.net/manual/en/book.enchant.php

PHP 5.3 deprecated pspell in favor of enchant, which is bundled with PHP by default. It's a wrapper library that supports aspell, hunspell, myspell, and others seamlessly...

**Comment by badsyntax** [comment]
Thanks again for the suggestion. I'll look into when I've got some time. I haven't used enchance before, feel free to provide an example or send a pull request.

**Comment by linuxscout** [comment]
I have added the hunspell driver, on 
https://gist.github.com/4013847

**Comment by badsyntax** [comment]
Thanks for the gist linuxscout, are you able to rather send a pull request?

In an case, I've decided to go with the Enchant approach and have pushed a simple Enchant driver with commit: 82eae6fe8df1eb2f1c7355d02603973c3fc7a65e

**Comment by badsyntax** [comment]
I've added an enchant driver and it seems to be working fine for me, so I'm going to close this ticket. If you would like to test the enchant driver, please use v0.2.3, and let me know if there are any issues!
