### ISSUE TITLE
There was an error processing the request. (Resolved)

### ISSUE THREAD

**Issue by gianmaria88** [badsyntax/jquery-spellchecker#59]
Hi, I downloaded the plugin and than I uploaded on my website, but when I try to click on any button the page alert this error. What is wrong? How do I install correctly the plugin?
Please help me
Thank you

**Comment by khubbaib** [comment]
@gianmaria88 how to resolved this issue? I am also facing this error.

**Comment by gianmaria88** [comment]
The problem was caused by the driver (google, enchant,...) that doesn't run. Resolved installing a custom driver fetching data from my database.

**Comment by khubbaib** [comment]
@gianmaria88  how i can install the drivers in local computer like wamp or xampp. i had installed aspell library but its not work

**Comment by andrewmth** [comment]
I am also facing this error.

**Comment by dhunink** [comment]
Strangely enough it also occurs in the online demo's...
